[motion]
DEADZONE = {VX = 0.0001, VW = 0.006, PV = 0.04, PS = 0.00002}
DELAY = {VX = 0.15, VW = 0.15, PV = 0.15, PS = 0.15, LOCALIZATION = 0.10}
USE_DIFFERENT_WHEELBASE = false
STEERING_DRIVE_ANGLE_OFFSET = {SIGN = 1.0, USE_DYNAMIC_STEERING_DRIVE_ANGLE = true, USE_SAME_STEERING_DRIVE_ANGLE = false, FORWARD = 1.0, BACKWARD = -4.0}
Lw = 0.9
DRIVE_TYPE = 3
INITAL_ROTATE_ANGLE = 1.57

[motion_constraint]
EXTREME = [ 1.5, 0.5, 3.5, 10.0, 0.5, 1.0, 1.2, 10.0,]
FAST = [ 1.5, 0.5, 2.0, 5.0, 0.5, 0.6, 1.5, 5.0,]
REGULAR = [ 0.9, 0.6, 1.5, 4.0, 0.5, 1.0, 1.5, 4.0,]
SMOOTH = [ 0.7, 0.6, 1.5, 5.0, 0.5, 0.8, 1.0, 5.0,]
SLOW = [ 0.5, 0.45, 1.5, 5.0, 0.5, 0.4, 0.8, 5.0,]
PUSH = [ 0.1, 0.05, 1.0, 2.0, 0.5, 0.4, 0.8, 3.0,]

[local_planner]
FRONT_THRESHOLD = 0.15
REAR_THRESHOLD = 0.05
MINIMUM_THRESHOLD = 0.1
HALF_WIDTH_THRESHOLD = 0.1
Obstacle_Stop_Dist = [ 0.5, 1.0, 1.5,]
Obstacle_Stop_Vel_Limit_Factor = [0.3, 0.8, 1.0,]
GLOBAL_PATH_LENGTH = [0.5, 1.0, 2.0, 3.0, 3.5, 4.0]
GLOBAL_PATH_VEL = [0.2, 0.3, 0.5, 0.8, 1.0, 1.5]
LINEAR_VEL_GAIN = 4.0
ANGULAR_VEL_GAIN = 4.0
IN_PLACE_ROTATION_OMEGA_MAX = 0.4
OBSTACLE_STOP_DIST = 0

[push]
use_closed_loop_push = true
push_gas = 22
push_down_distance = 0.03
accurate_push_down_distance = 0.20


[move_controller]
MC_bangbangMaxLonSpeedFactor = 2.0  #should >= 2.0

[speed_controller]
is_calib = false
enable = true

td_r = 15

# gas pd controller params
is_nonlinear_pid = false
gas_pd_magnitude = 100
gas_fb_pd_vel_list = [ 0.1, 0.2, 0.6, 0.9, 1.5,]
gas_fb_p_list = [ 0.4, 0.4, 0.8, 0.05, 0.05,]
gas_fb_d_list = [ 0.2, 0.2, 0.1, 0.05, 0.05,]
gas_fb_i = 0.1
gas_in_brake_value = 0.0
gas_in_brake_factor = 0.1
start_up_speed = 0.04
delay_vel = 0.2

# gas params
gas_value_smooth = 25
gas_value_max_vel_list = [0.05, 0.12, 0.15, 0.9]
gas_value_max_list = [22, 30, 50, 60]
gas_factor_vel_list = [0.0, 0.1, 0.2, 0.95]
gas_factor_list = [1.3, 1.3, 1.0, 0.95]
gas_list = [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60,]
speed_list = [ 0.0, 0.05, 0.11, 0.2, 0.33, 0.5, 0.67, 0.84, 1.01, 1.18, 1.35, 1.52,]

brake_enable = true
brake_factor = 1.0
brake_factor_vel_list = [0.9, 1.2, 1.5]
brake_factor_list = [1.0, 1.5, 2.0]
brake_acc_threshold = 0.1
brake_value_smooth = 40
brake_value_max = 50
brake_delay = 0.3
brake_acc_list = [0.0, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0, 3.2, 3.4, 3.6]
brake_value_list = [0, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]

[angle_controller]
td_r = 15
delay_angle = 0.2
angle_value_max = 60.0
angle_pd_magnitude = 100
angle_pd_vel_list = [0.0, 0.6, 0.9, 1.2, 1.5,]
angle_p_list = [2.0, 2.0, 1.5, 1.0, 0.8,]
angle_d_list = [0.6, 0.6, 0.6, 0.6, 0.6]
angle_value_max_error_list = [ 0.2, 0.4, 0.6, 0.8,]
angle_value_max_list = [ 100, 80, 60, 50,]

[lidar]
USE_FRONT_LIDAR = true
USE_BACK_LIDAR = true

[Globals]
gStartupSpeedMetersPerSec = 0.1
gMoveControlThreadFreqTolFactor = 0.6
gSteeringDriveOffsetLearningSpeed = 0.1
gTaskFinishYawDiffLimit = 2.5
gTaskFinishPoseDistLimit = 0.10
gCurvatureEnhancedFactor = 2.5
gAccurateLongitudinalTolMeters = 0.007

[TOF]
TOF_type = "OBS_AVOID"
TOF_module = "TOF_RANGE"
TOF_FIELD_OF_VIEW = 0.01745
TOF_MIN_RANGE = 0.03
TOF_MAX_RANGE = 5.0
TOF_INTENSITY_LOWER_BOUND = 1000.0
TOF_INTENSITY_UPPER_BOUND = 65535.0
